unit SetupCol;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ComCtrls, Buttons, ExtCtrls
type
  TfrmSetupCols=class(TForm)
    Label1: TLabel;
    Label2: TLabel;
    lblDragAndDrop: TLabel;
    Bevel1: TBevel;
    lblWidth: TLabel;
    btnAdd: TButton;
    btnAddAll: TButton;
    btnRemove: TButton;
    btnRemoveAll: TButton;
    lblSort: TLabel;
    btnSortUp: TBitBtn;
    btnSortDown: TBitBtn;
    Bevel2: TBevel;
    lvCur: TListView;
    lvAvail: TListView;
    udWidth: TUpDown;
    edWidth: TEdit;
    btnOK: TButton;
    btnCancel: TButton;
    btnApply: TButton;
    btnHelp: TButton;
    btnUp: TButton;
    btnDown: TButton;
//    OFFS_0368: N.A.;
    procedure FormCreate(Sender : TObject);
    procedure LVClick(Sender : TObject);
    procedure btnModifyClick(Sender : TObject);
    procedure btnApplyClick(Sender : TObject);
    procedure edWidthChange(Sender : TObject);
    procedure AvailLB1DragDrop(Sender : TObject);
    procedure AvailLB1DragOver(Sender : TObject);
    procedure CurLB1DragOver(Sender : TObject);
    procedure CurLB1DragDrop(Sender : TObject);
    procedure LVSelectItem(Sender : TObject);
    procedure btnHelpClick(Sender : TObject);
    procedure _PROC_004D4468(Sender : TObject);
    procedure _PROC_004D44DC(Sender : TObject);
    procedure _PROC_004D4554(Sender : TObject);
    procedure _PROC_004D457C(Sender : TObject);
    procedure _PROC_004D46F0(Sender : TObject);
    procedure _PROC_004D48FC(Sender : TObject);
    procedure _PROC_004D4FE0(Sender : TObject);
    procedure _PROC_004D5010(Sender : TObject);
    procedure _PROC_004D5018(Sender : TObject);
    procedure _PROC_004D50A2(Sender : TObject);
    procedure _PROC_004D511A(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmSetupCols: TfrmSetupCols;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmSetupCols.FormCreate(Sender : TObject);
begin
(*
004D4770   55                     push    ebp
004D4771   8BEC                   mov     ebp, esp
004D4773   51                     push    ecx
004D4774   53                     push    ebx
004D4775   56                     push    esi
004D4776   57                     push    edi
004D4777   8BD8                   mov     ebx, eax
004D4779   8B15342A5000           mov     edx, [$00502A34]
004D477F   8B12                   mov     edx, [edx]
004D4781   8BC3                   mov     eax, ebx

|
004D4783   E84CD00100             call    004F17D4

* Reference to control TfrmSetupCols.lblDragAndDrop : TLabel
|
004D4788   8B8300030000           mov     eax, [ebx+$0300]
004D478E   8945FC                 mov     [ebp-$04], eax
004D4791   8D55FC                 lea     edx, [ebp-$04]
004D4794   33C9                   xor     ecx, ecx
004D4796   8BC3                   mov     eax, ebx

|
004D4798   E8F3CF0100             call    004F1790

* Reference to field TfrmSetupCols.OFFS_0360
|
004D479D   8BBB60030000           mov     edi, [ebx+$0360]
004D47A3   85FF                   test    edi, edi
004D47A5   7E63                   jle     004D480A
004D47A7   BE01000000             mov     esi, $00000001
004D47AC   8D0476                 lea     eax, [esi+esi*2]

* Reference to field TfrmSetupCols.OFFS_0358
|
004D47AF   8B9358030000           mov     edx, [ebx+$0358]
004D47B5   8B4482F4               mov     eax, [edx+eax*4-$0C]
004D47B9   85C0                   test    eax, eax
004D47BB   7E1D                   jle     004D47DA
004D47BD   6AFF                   push    $FF
004D47BF   50                     push    eax

* Reference to field TfrmSetupCols.OFFS_035C
|
004D47C0   8B935C030000           mov     edx, [ebx+$035C]
004D47C6   8B4482FC               mov     eax, [edx+eax*4-$04]
004D47CA   8B10                   mov     edx, [eax]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D47CC   8B832C030000           mov     eax, [ebx+$032C]
004D47D2   59                     pop     ecx

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D47D3   E890FCFFFF             call    004D4468
004D47D8   EB2C                   jmp     004D4806
004D47DA   6AFF                   push    $FF
004D47DC   8D1476                 lea     edx, [esi+esi*2]

* Reference to field TfrmSetupCols.OFFS_0358
|
004D47DF   8B8B58030000           mov     ecx, [ebx+$0358]
004D47E5   8B5491F4               mov     edx, [ecx+edx*4-$0C]
004D47E9   F7DA                   neg     edx 
004D47EB   52                     push    edx
004D47EC   F7D8                   neg     eax 

* Reference to field TfrmSetupCols.OFFS_035C
|
004D47EE   8B935C030000           mov     edx, [ebx+$035C]
004D47F4   8B4482FC               mov     eax, [edx+eax*4-$04]
004D47F8   8B10                   mov     edx, [eax]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D47FA   8B8330030000           mov     eax, [ebx+$0330]
004D4800   59                     pop     ecx

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D4801   E862FCFFFF             call    004D4468
004D4806   46                     inc     esi
004D4807   4F                     dec     edi
004D4808   75A2                   jnz     004D47AC

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D480A   8B832C030000           mov     eax, [ebx+$032C]

* Reference to field TListView.Items : TListItems
|
004D4810   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D4816   E8359AF8FF             call    0045E250
004D481B   85C0                   test    eax, eax
004D481D   7E51                   jle     004D4870

* Reference to field TfrmSetupCols.OFFS_0368 : Byte
|
004D481F   80BB6803000000         cmp     byte ptr [ebx+$0368], $00
004D4826   7425                   jz      004D484D

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4828   8B832C030000           mov     eax, [ebx+$032C]

* Reference to field TListView.Items : TListItems
|
004D482E   8B802C020000           mov     eax, [eax+$022C]

* Reference to field TfrmSetupCols.OFFS_0364
|
004D4834   8B9364030000           mov     edx, [ebx+$0364]

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D483A   E8419AF8FF             call    0045E280
004D483F   B921000000             mov     ecx, $00000021
004D4844   33D2                   xor     edx, edx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D4846   E8F595F8FF             call    0045DE40
004D484B   EB23                   jmp     004D4870

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D484D   8B832C030000           mov     eax, [ebx+$032C]

* Reference to field TListView.Items : TListItems
|
004D4853   8B802C020000           mov     eax, [eax+$022C]

* Reference to field TfrmSetupCols.OFFS_0364
|
004D4859   8B9364030000           mov     edx, [ebx+$0364]

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D485F   E81C9AF8FF             call    0045E280
004D4864   B920000000             mov     ecx, $00000020
004D4869   33D2                   xor     edx, edx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D486B   E8D095F8FF             call    0045DE40
004D4870   8BC3                   mov     eax, ebx

* Reference to : TfrmSetupCols._PROC_004D457C()
|
004D4872   E805FDFFFF             call    004D457C
004D4877   5F                     pop     edi
004D4878   5E                     pop     esi
004D4879   5B                     pop     ebx
004D487A   59                     pop     ecx
004D487B   5D                     pop     ebp
004D487C   C3                     ret

*)
end;

procedure TfrmSetupCols.LVClick(Sender : TObject);
begin
(*
004D4880   55                     push    ebp
004D4881   8BEC                   mov     ebp, esp

* Reference to : TfrmSetupCols._PROC_004D457C()
|
004D4883   E8F4FCFFFF             call    004D457C
004D4888   5D                     pop     ebp
004D4889   C3                     ret

*)
end;

procedure TfrmSetupCols.btnModifyClick(Sender : TObject);
begin
(*
004D488C   55                     push    ebp
004D488D   8BEC                   mov     ebp, esp
004D488F   51                     push    ecx
004D4890   53                     push    ebx
004D4891   56                     push    esi
004D4892   57                     push    edi
004D4893   8BFA                   mov     edi, edx
004D4895   8945FC                 mov     [ebp-$04], eax
004D4898   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D489B   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D48A1   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.BeginUpdate(TListItems);
|
004D48A7   E8B89AF8FF             call    0045E364
004D48AC   33D2                   xor     edx, edx
004D48AE   55                     push    ebp
004D48AF   680E4C4D00             push    $004D4C0E

***** TRY
|
004D48B4   64FF32                 push    dword ptr fs:[edx]
004D48B7   648922                 mov     fs:[edx], esp
004D48BA   8B470C                 mov     eax, [edi+$0C]
004D48BD   83F808                 cmp     eax, +$08
004D48C0   0F8726030000           jnbe    004D4BEC
004D48C6   FF2485CD484D00         jmp     dword ptr [$4D48CD+eax*4]
004D48CD   EC                     in      al, dx
004D48CE   4B                     dec     ebx
004D48CF   4D                     dec     ebp
004D48D0   00F1                   add     cl, dh
004D48D2   48                     dec     eax
004D48D3   4D                     dec     ebp
004D48D4   004A49                 add     [edx+$49], cl
004D48D7   4D                     dec     ebp
004D48D8   00B3494D000C           add     [ebx+$C004D49], dh
004D48DE   4A                     dec     edx
004D48DF   4D                     dec     ebp
004D48E0   00754A                 add     [ebp+$4A], dh
004D48E3   4D                     dec     ebp
004D48E4   00F4                   add     ah, dh
004D48E6   4A                     dec     edx
004D48E7   4D                     dec     ebp
004D48E8   006E4B                 add     [esi+$4B], ch
004D48EB   4D                     dec     ebp
004D48EC   006E4B                 add     [esi+$4B], ch
004D48EF   4D                     dec     ebp
004D48F0   008B45FC8B80           add     [ebx+$808BFC45], cl
004D48F6   3003                   xor     [ebx], al
004D48F8   0000                   add     [eax], al

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D48FA   E855FCFFFF             call    004D4554
004D48FF   8BD8                   mov     ebx, eax
004D4901   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4904   8B8030030000           mov     eax, [eax+$0330]

* Reference to field TListView.Items : TListItems
|
004D490A   8B802C020000           mov     eax, [eax+$022C]
004D4910   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4912   E86999F8FF             call    0045E280

* Reference to field TListItems.OFFS_0010
|
004D4917   8B5010                 mov     edx, [eax+$10]
004D491A   52                     push    edx

* Reference to field TListItems.OFFS_000C
|
004D491B   8B480C                 mov     ecx, [eax+$0C]

* Reference to field TListItems.OFFS_0024
|
004D491E   8B5024                 mov     edx, [eax+$24]
004D4921   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4924   8B802C030000           mov     eax, [eax+$032C]

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D492A   E839FBFFFF             call    004D4468
004D492F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4932   8B8030030000           mov     eax, [eax+$0330]

* Reference to field TListView.Items : TListItems
|
004D4938   8B802C020000           mov     eax, [eax+$022C]
004D493E   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4940   E807A2F8FF             call    0045EB4C
004D4945   E9A2020000             jmp     004D4BEC
004D494A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D494D   8B8030030000           mov     eax, [eax+$0330]

* Reference to field TListView.Items : TListItems
|
004D4953   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D4959   E8F298F8FF             call    0045E250
004D495E   8BD8                   mov     ebx, eax
004D4960   4B                     dec     ebx
004D4961   85DB                   test    ebx, ebx
004D4963   7C35                   jl      004D499A
004D4965   43                     inc     ebx
004D4966   33F6                   xor     esi, esi
004D4968   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D496B   8B8030030000           mov     eax, [eax+$0330]

* Reference to field TListView.Items : TListItems
|
004D4971   8B802C020000           mov     eax, [eax+$022C]
004D4977   8BD6                   mov     edx, esi

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4979   E80299F8FF             call    0045E280

* Reference to field TListItems.OFFS_0010
|
004D497E   8B5010                 mov     edx, [eax+$10]
004D4981   52                     push    edx

* Reference to field TListItems.OFFS_000C
|
004D4982   8B480C                 mov     ecx, [eax+$0C]

* Reference to field TListItems.OFFS_0024
|
004D4985   8B5024                 mov     edx, [eax+$24]
004D4988   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D498B   8B802C030000           mov     eax, [eax+$032C]

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D4991   E8D2FAFFFF             call    004D4468
004D4996   46                     inc     esi
004D4997   4B                     dec     ebx
004D4998   75CE                   jnz     004D4968
004D499A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D499D   8B8030030000           mov     eax, [eax+$0330]

* Reference to field TListView.Items : TListItems
|
004D49A3   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.Clear(TListItems);
|
004D49A9   E89699F8FF             call    0045E344
004D49AE   E939020000             jmp     004D4BEC
004D49B3   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D49B6   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D49BC   E893FBFFFF             call    004D4554
004D49C1   8BD8                   mov     ebx, eax
004D49C3   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D49C6   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D49CC   8B802C020000           mov     eax, [eax+$022C]
004D49D2   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D49D4   E8A798F8FF             call    0045E280

* Reference to field TListItems.OFFS_0010
|
004D49D9   8B5010                 mov     edx, [eax+$10]
004D49DC   52                     push    edx

* Reference to field TListItems.OFFS_000C
|
004D49DD   8B480C                 mov     ecx, [eax+$0C]

* Reference to field TListItems.OFFS_0024
|
004D49E0   8B5024                 mov     edx, [eax+$24]
004D49E3   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D49E6   8B8030030000           mov     eax, [eax+$0330]

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D49EC   E877FAFFFF             call    004D4468
004D49F1   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D49F4   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D49FA   8B802C020000           mov     eax, [eax+$022C]
004D4A00   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4A02   E845A1F8FF             call    0045EB4C
004D4A07   E9E0010000             jmp     004D4BEC
004D4A0C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4A0F   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4A15   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D4A1B   E83098F8FF             call    0045E250
004D4A20   8BD8                   mov     ebx, eax
004D4A22   4B                     dec     ebx
004D4A23   85DB                   test    ebx, ebx
004D4A25   7C35                   jl      004D4A5C
004D4A27   43                     inc     ebx
004D4A28   33F6                   xor     esi, esi
004D4A2A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4A2D   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4A33   8B802C020000           mov     eax, [eax+$022C]
004D4A39   8BD6                   mov     edx, esi

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4A3B   E84098F8FF             call    0045E280

* Reference to field TListItems.OFFS_0010
|
004D4A40   8B5010                 mov     edx, [eax+$10]
004D4A43   52                     push    edx

* Reference to field TListItems.OFFS_000C
|
004D4A44   8B480C                 mov     ecx, [eax+$0C]

* Reference to field TListItems.OFFS_0024
|
004D4A47   8B5024                 mov     edx, [eax+$24]
004D4A4A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4A4D   8B8030030000           mov     eax, [eax+$0330]

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D4A53   E810FAFFFF             call    004D4468
004D4A58   46                     inc     esi
004D4A59   4B                     dec     ebx
004D4A5A   75CE                   jnz     004D4A2A
004D4A5C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4A5F   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4A65   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.Clear(TListItems);
|
004D4A6B   E8D498F8FF             call    0045E344
004D4A70   E977010000             jmp     004D4BEC
004D4A75   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4A78   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D4A7E   E8D1FAFFFF             call    004D4554
004D4A83   8BD8                   mov     ebx, eax
004D4A85   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4A88   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4A8E   8B802C020000           mov     eax, [eax+$022C]
004D4A94   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4A96   E8E597F8FF             call    0045E280

* Reference to field TListItems.OFFS_000C
|
004D4A9B   8B500C                 mov     edx, [eax+$0C]
004D4A9E   52                     push    edx

* Reference to field TListItems.OFFS_0010
|
004D4A9F   8B5010                 mov     edx, [eax+$10]
004D4AA2   52                     push    edx

* Reference to field TListItems.OFFS_0024
|
004D4AA3   8B4824                 mov     ecx, [eax+$24]
004D4AA6   8BF3                   mov     esi, ebx
004D4AA8   4E                     dec     esi
004D4AA9   8BD6                   mov     edx, esi
004D4AAB   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4AAE   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D44DC()
|
004D4AB4   E823FAFFFF             call    004D44DC

* Reference to field TListView.OFFS_0001
|
004D4AB9   8D5301                 lea     edx, [ebx+$01]
004D4ABC   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4ABF   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4AC5   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4ACB   E87CA0F8FF             call    0045EB4C
004D4AD0   8BD6                   mov     edx, esi
004D4AD2   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4AD5   8BB82C030000           mov     edi, [eax+$032C]
004D4ADB   8B872C020000           mov     eax, [edi+$022C]

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4AE1   E89A97F8FF             call    0045E280
004D4AE6   8BD0                   mov     edx, eax
004D4AE8   8BC7                   mov     eax, edi

* Reference to: ComCtrls.TCustomListView.SetSelected(TCustomListView;TListItem);
|
004D4AEA   E851CEF8FF             call    00461940
004D4AEF   E9F8000000             jmp     004D4BEC
004D4AF4   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4AF7   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D4AFD   E852FAFFFF             call    004D4554
004D4B02   8BD8                   mov     ebx, eax
004D4B04   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4B07   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4B0D   8B802C020000           mov     eax, [eax+$022C]
004D4B13   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4B15   E86697F8FF             call    0045E280

* Reference to field TListItems.OFFS_000C
|
004D4B1A   8B500C                 mov     edx, [eax+$0C]
004D4B1D   52                     push    edx

* Reference to field TListItems.OFFS_0010
|
004D4B1E   8B5010                 mov     edx, [eax+$10]
004D4B21   52                     push    edx

* Reference to field TListItems.OFFS_0024
|
004D4B22   8B4824                 mov     ecx, [eax+$24]

* Reference to field TListView.OFFS_0002
|
004D4B25   8D5302                 lea     edx, [ebx+$02]
004D4B28   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4B2B   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D44DC()
|
004D4B31   E8A6F9FFFF             call    004D44DC
004D4B36   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4B39   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4B3F   8B802C020000           mov     eax, [eax+$022C]
004D4B45   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4B47   E800A0F8FF             call    0045EB4C

* Reference to field TListView.OFFS_0001
|
004D4B4C   8D5301                 lea     edx, [ebx+$01]
004D4B4F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4B52   8BB02C030000           mov     esi, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4B58   8B862C020000           mov     eax, [esi+$022C]

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4B5E   E81D97F8FF             call    0045E280
004D4B63   8BD0                   mov     edx, eax
004D4B65   8BC6                   mov     eax, esi

* Reference to: ComCtrls.TCustomListView.SetSelected(TCustomListView;TListItem);
|
004D4B67   E8D4CDF8FF             call    00461940
004D4B6C   EB7E                   jmp     004D4BEC
004D4B6E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4B71   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4B77   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D4B7D   E8CE96F8FF             call    0045E250
004D4B82   8BD8                   mov     ebx, eax
004D4B84   4B                     dec     ebx
004D4B85   85DB                   test    ebx, ebx
004D4B87   7C27                   jl      004D4BB0
004D4B89   43                     inc     ebx
004D4B8A   33F6                   xor     esi, esi
004D4B8C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4B8F   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4B95   8B802C020000           mov     eax, [eax+$022C]
004D4B9B   8BD6                   mov     edx, esi

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4B9D   E8DE96F8FF             call    0045E280
004D4BA2   83C9FF                 or      ecx, -$01
004D4BA5   33D2                   xor     edx, edx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D4BA7   E89492F8FF             call    0045DE40
004D4BAC   46                     inc     esi
004D4BAD   4B                     dec     ebx
004D4BAE   75DC                   jnz     004D4B8C
004D4BB0   837F0C07               cmp     dword ptr [edi+$0C], +$07
004D4BB4   751C                   jnz     004D4BD2
004D4BB6   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4BB9   8B802C030000           mov     eax, [eax+$032C]

* Reference to: ComCtrls.TCustomListView.GetSelected(TCustomListView):TListItem;
|
004D4BBF   E864CDF8FF             call    00461928
004D4BC4   B920000000             mov     ecx, $00000020
004D4BC9   33D2                   xor     edx, edx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D4BCB   E87092F8FF             call    0045DE40
004D4BD0   EB1A                   jmp     004D4BEC
004D4BD2   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4BD5   8B802C030000           mov     eax, [eax+$032C]

* Reference to: ComCtrls.TCustomListView.GetSelected(TCustomListView):TListItem;
|
004D4BDB   E848CDF8FF             call    00461928
004D4BE0   B921000000             mov     ecx, $00000021
004D4BE5   33D2                   xor     edx, edx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D4BE7   E85492F8FF             call    0045DE40
004D4BEC   33C0                   xor     eax, eax
004D4BEE   5A                     pop     edx
004D4BEF   59                     pop     ecx
004D4BF0   59                     pop     ecx
004D4BF1   648910                 mov     fs:[eax], edx

****** FINALLY
|
004D4BF4   68154C4D00             push    $004D4C15
004D4BF9   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4BFC   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4C02   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.EndUpdate(TListItems);
|
004D4C08   E83399F8FF             call    0045E540
004D4C0D   C3                     ret


* Reference to: System.@HandleFinally;
|
004D4C0E   E905F8F2FF             jmp     00404418
004D4C13   EBE4                   jmp     004D4BF9

****** END
|
004D4C15   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TfrmSetupCols._PROC_004D457C()
|
004D4C18   E85FF9FFFF             call    004D457C
004D4C1D   5F                     pop     edi
004D4C1E   5E                     pop     esi
004D4C1F   5B                     pop     ebx
004D4C20   59                     pop     ecx
004D4C21   5D                     pop     ebp
004D4C22   C3                     ret

*)
end;

procedure TfrmSetupCols.btnApplyClick(Sender : TObject);
begin
(*
004D4C24   55                     push    ebp
004D4C25   8BEC                   mov     ebp, esp
004D4C27   51                     push    ecx
004D4C28   53                     push    ebx
004D4C29   56                     push    esi
004D4C2A   57                     push    edi
004D4C2B   8BF0                   mov     esi, eax

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4C2D   8B862C030000           mov     eax, [esi+$032C]

* Reference to field TListView.Items : TListItems
|
004D4C33   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D4C39   E81296F8FF             call    0045E250
004D4C3E   8945FC                 mov     [ebp-$04], eax
004D4C41   8B7DFC                 mov     edi, [ebp-$04]
004D4C44   85FF                   test    edi, edi
004D4C46   7E2D                   jle     004D4C75
004D4C48   BB01000000             mov     ebx, $00000001
004D4C4D   8BD3                   mov     edx, ebx
004D4C4F   4A                     dec     edx

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4C50   8B862C030000           mov     eax, [esi+$032C]

* Reference to field TListView.Items : TListItems
|
004D4C56   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4C5C   E81F96F8FF             call    0045E280

* Reference to field TListItems.OFFS_000C
|
004D4C61   8B400C                 mov     eax, [eax+$0C]
004D4C64   8D145B                 lea     edx, [ebx+ebx*2]

* Reference to field TfrmSetupCols.OFFS_0358
|
004D4C67   8B8E58030000           mov     ecx, [esi+$0358]
004D4C6D   894491F4               mov     [ecx+edx*4-$0C], eax
004D4C71   43                     inc     ebx
004D4C72   4F                     dec     edi
004D4C73   75D8                   jnz     004D4C4D

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4C75   8B8630030000           mov     eax, [esi+$0330]

* Reference to field TListView.Items : TListItems
|
004D4C7B   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D4C81   E8CA95F8FF             call    0045E250
004D4C86   8BF8                   mov     edi, eax
004D4C88   85FF                   test    edi, edi
004D4C8A   7E34                   jle     004D4CC0
004D4C8C   BB01000000             mov     ebx, $00000001
004D4C91   8BD3                   mov     edx, ebx
004D4C93   4A                     dec     edx

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4C94   8B8630030000           mov     eax, [esi+$0330]

* Reference to field TListView.Items : TListItems
|
004D4C9A   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4CA0   E8DB95F8FF             call    0045E280

* Reference to field TListItems.OFFS_000C
|
004D4CA5   8B400C                 mov     eax, [eax+$0C]
004D4CA8   F7D8                   neg     eax 
004D4CAA   8B55FC                 mov     edx, [ebp-$04]
004D4CAD   03D3                   add     edx, ebx
004D4CAF   8D1452                 lea     edx, [edx+edx*2]

* Reference to field TfrmSetupCols.OFFS_0358
|
004D4CB2   8B8E58030000           mov     ecx, [esi+$0358]
004D4CB8   894491F4               mov     [ecx+edx*4-$0C], eax
004D4CBC   43                     inc     ebx
004D4CBD   4F                     dec     edi
004D4CBE   75D1                   jnz     004D4C91
004D4CC0   33C0                   xor     eax, eax

* Reference to field TfrmSetupCols.OFFS_0364
|
004D4CC2   898664030000           mov     [esi+$0364], eax

* Reference to field TfrmSetupCols.OFFS_0368 : Byte
|
004D4CC8   C6866803000001         mov     byte ptr [esi+$0368], $01

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4CCF   8B862C030000           mov     eax, [esi+$032C]

* Reference to field TListView.Items : TListItems
|
004D4CD5   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D4CDB   E87095F8FF             call    0045E250
004D4CE0   8BF8                   mov     edi, eax
004D4CE2   4F                     dec     edi
004D4CE3   85FF                   test    edi, edi
004D4CE5   7C39                   jl      004D4D20
004D4CE7   47                     inc     edi
004D4CE8   33DB                   xor     ebx, ebx

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4CEA   8B862C030000           mov     eax, [esi+$032C]

* Reference to field TListView.Items : TListItems
|
004D4CF0   8B802C020000           mov     eax, [eax+$022C]
004D4CF6   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4CF8   E88395F8FF             call    0045E280

* Reference to field TListItems.OFFS_0010
|
004D4CFD   8B4010                 mov     eax, [eax+$10]
004D4D00   8945FC                 mov     [ebp-$04], eax
004D4D03   837DFCFF               cmp     dword ptr [ebp-$04], -$01
004D4D07   7413                   jz      004D4D1C

* Reference to field TfrmSetupCols.OFFS_0364
|
004D4D09   899E64030000           mov     [esi+$0364], ebx
004D4D0F   837DFC21               cmp     dword ptr [ebp-$04], +$21
004D4D13   0F94C0                 setz    al

* Reference to field TfrmSetupCols.OFFS_0368 : Byte
|
004D4D16   888668030000           mov     [esi+$0368], al
004D4D1C   43                     inc     ebx
004D4D1D   4F                     dec     edi
004D4D1E   75CA                   jnz     004D4CEA
004D4D20   A168265000             mov     eax, dword ptr [$00502668]

* Reference to field TfrmSetupCols.OFFS_0364
|
004D4D25   8B9664030000           mov     edx, [esi+$0364]
004D4D2B   8910                   mov     [eax], edx
004D4D2D   A1E4255000             mov     eax, dword ptr [$005025E4]

* Reference to field TfrmSetupCols.OFFS_0368 : Byte
|
004D4D32   8A9668030000           mov     dl, byte ptr [esi+$0368]
004D4D38   8810                   mov     [eax], dl
004D4D3A   A1342A5000             mov     eax, dword ptr [$00502A34]
004D4D3F   8B00                   mov     eax, [eax]

|
004D4D41   E882090100             call    004E56C8
004D4D46   5F                     pop     edi
004D4D47   5E                     pop     esi
004D4D48   5B                     pop     ebx
004D4D49   59                     pop     ecx
004D4D4A   5D                     pop     ebp
004D4D4B   C3                     ret

*)
end;

procedure TfrmSetupCols.edWidthChange(Sender : TObject);
begin
(*
004D4D4C   55                     push    ebp
004D4D4D   8BEC                   mov     ebp, esp
004D4D4F   83C4F8                 add     esp, -$08
004D4D52   53                     push    ebx
004D4D53   56                     push    esi
004D4D54   57                     push    edi
004D4D55   8945FC                 mov     [ebp-$04], eax
004D4D58   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4D5B   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D4D61   E8EEF7FFFF             call    004D4554
004D4D66   8945F8                 mov     [ebp-$08], eax
004D4D69   837DF8FF               cmp     dword ptr [ebp-$08], -$01
004D4D6D   747F                   jz      004D4DEE
004D4D6F   33C0                   xor     eax, eax
004D4D71   55                     push    ebp
004D4D72   68C84D4D00             push    $004D4DC8

***** TRY
|
004D4D77   64FF30                 push    dword ptr fs:[eax]
004D4D7A   648920                 mov     fs:[eax], esp
004D4D7D   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4D80   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4D86   8B802C020000           mov     eax, [eax+$022C]
004D4D8C   8B55F8                 mov     edx, [ebp-$08]

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4D8F   E8EC94F8FF             call    0045E280

* Reference to field TListItems.OFFS_000C
|
004D4D94   8B400C                 mov     eax, [eax+$0C]
004D4D97   8945F8                 mov     [ebp-$08], eax
004D4D9A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.udWidth : TUpDown
|
004D4D9D   8B8034030000           mov     eax, [eax+$0334]

* Reference to: ComCtrls.TCustomUpDown.GetPosition(TCustomUpDown):Smallint;
|
004D4DA3   E8C479F8FF             call    0045C76C
004D4DA8   0FBFC0                 movsx   eax, ax
004D4DAB   8B55F8                 mov     edx, [ebp-$08]
004D4DAE   8D1452                 lea     edx, [edx+edx*2]
004D4DB1   8B4DFC                 mov     ecx, [ebp-$04]
004D4DB4   8B8958030000           mov     ecx, [ecx+$0358]
004D4DBA   894491F8               mov     [ecx+edx*4-$08], eax
004D4DBE   33C0                   xor     eax, eax
004D4DC0   5A                     pop     edx
004D4DC1   59                     pop     ecx
004D4DC2   59                     pop     ecx
004D4DC3   648910                 mov     fs:[eax], edx
004D4DC6   EB26                   jmp     004D4DEE

* Reference to: System.@HandleAnyException;
|
004D4DC8   E997F3F2FF             jmp     00404164
004D4DCD   8B45F8                 mov     eax, [ebp-$08]
004D4DD0   8D0440                 lea     eax, [eax+eax*2]
004D4DD3   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TfrmSetupCols.OFFS_0358
|
004D4DD6   8B9258030000           mov     edx, [edx+$0358]
004D4DDC   C74482F832000000       mov     dword ptr [edx+eax*4-$08], $00000032

* Reference to: Classes.TStream.WriteComponentRes(TStream;AnsiString;TComponent);
|
004D4DE4   E83F8FF3FF             call    0040DD28

* Reference to: System.@DoneExcept;
|
004D4DE9   E8DEF6F2FF             call    004044CC

****** END
|
004D4DEE   5F                     pop     edi
004D4DEF   5E                     pop     esi
004D4DF0   5B                     pop     ebx
004D4DF1   59                     pop     ecx
004D4DF2   59                     pop     ecx
004D4DF3   5D                     pop     ebp
004D4DF4   C3                     ret

*)
end;

procedure TfrmSetupCols.AvailLB1DragDrop(Sender : TObject);
begin
(*
004D4DF8   55                     push    ebp
004D4DF9   8BEC                   mov     ebp, esp
004D4DFB   56                     push    esi

* Reference to control TfrmSetupCols.btnRemove : TButton
|
004D4DFC   8B8014030000           mov     eax, [eax+$0314]
004D4E02   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
004D4E06   E875F0F2FF             call    00403E80
004D4E0B   5E                     pop     esi
004D4E0C   5D                     pop     ebp
004D4E0D   C20800                 ret     $0008

*)
end;

procedure TfrmSetupCols.AvailLB1DragOver(Sender : TObject);
begin
(*
004D4E10   55                     push    ebp
004D4E11   8BEC                   mov     ebp, esp
004D4E13   53                     push    ebx
004D4E14   56                     push    esi
004D4E15   8BF1                   mov     esi, ecx
004D4E17   8BD8                   mov     ebx, eax

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4E19   3BB32C030000           cmp     esi, [ebx+$032C]
004D4E1F   750F                   jnz     004D4E30

* Reference to control TfrmSetupCols.btnRemove : TButton
|
004D4E21   8B8314030000           mov     eax, [ebx+$0314]
004D4E27   8B10                   mov     edx, [eax]

* Reference to method TButton.GetEnabled()
|
004D4E29   FF5250                 call    dword ptr [edx+$50]
004D4E2C   84C0                   test    al, al
004D4E2E   7504                   jnz     004D4E34
004D4E30   33C0                   xor     eax, eax
004D4E32   EB02                   jmp     004D4E36
004D4E34   B001                   mov     al, $01
004D4E36   8B5508                 mov     edx, [ebp+$08]
004D4E39   8802                   mov     [edx], al
004D4E3B   5E                     pop     esi
004D4E3C   5B                     pop     ebx
004D4E3D   5D                     pop     ebp
004D4E3E   C21000                 ret     $0010

*)
end;

procedure TfrmSetupCols.CurLB1DragOver(Sender : TObject);
begin
(*
004D4E44   55                     push    ebp
004D4E45   8BEC                   mov     ebp, esp
004D4E47   53                     push    ebx
004D4E48   8BD8                   mov     ebx, eax

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4E4A   3B8B30030000           cmp     ecx, [ebx+$0330]
004D4E50   7510                   jnz     004D4E62

* Reference to control TfrmSetupCols.btnAdd : TButton
|
004D4E52   8B830C030000           mov     eax, [ebx+$030C]
004D4E58   8B10                   mov     edx, [eax]

* Reference to method TButton.GetEnabled()
|
004D4E5A   FF5250                 call    dword ptr [edx+$50]
004D4E5D   8B5508                 mov     edx, [ebp+$08]
004D4E60   8802                   mov     [edx], al
004D4E62   5B                     pop     ebx
004D4E63   5D                     pop     ebp
004D4E64   C21000                 ret     $0010

*)
end;

procedure TfrmSetupCols.CurLB1DragDrop(Sender : TObject);
begin
(*
004D4E68   55                     push    ebp
004D4E69   8BEC                   mov     ebp, esp
004D4E6B   51                     push    ecx
004D4E6C   53                     push    ebx
004D4E6D   56                     push    esi
004D4E6E   8BD9                   mov     ebx, ecx
004D4E70   8945FC                 mov     [ebp-$04], eax
004D4E73   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4E76   8B802C030000           mov     eax, [eax+$032C]
004D4E7C   8B4D08                 mov     ecx, [ebp+$08]
004D4E7F   8B550C                 mov     edx, [ebp+$0C]

* Reference to: ComCtrls.TCustomListView.GetItemAt(TCustomListView;Integer;Integer):TListItem;
|
004D4E82   E8E5CCF8FF             call    00461B6C
004D4E87   85C0                   test    eax, eax
004D4E89   7409                   jz      004D4E94

* Reference to: ComCtrls.TListItem.GetIndex(TListItem):Integer;
|
004D4E8B   E82C92F8FF             call    0045E0BC
004D4E90   8BF0                   mov     esi, eax
004D4E92   EB02                   jmp     004D4E96
004D4E94   33F6                   xor     esi, esi
004D4E96   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4E99   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4E9F   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.BeginUpdate(TListItems);
|
004D4EA5   E8BA94F8FF             call    0045E364
004D4EAA   33D2                   xor     edx, edx
004D4EAC   55                     push    ebp
004D4EAD   68A64F4D00             push    $004D4FA6

***** TRY
|
004D4EB2   64FF32                 push    dword ptr fs:[edx]
004D4EB5   648922                 mov     fs:[edx], esp
004D4EB8   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4EBB   8B8030030000           mov     eax, [eax+$0330]
004D4EC1   3BD8                   cmp     ebx, eax
004D4EC3   7550                   jnz     004D4F15

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D4EC5   E88AF6FFFF             call    004D4554
004D4ECA   8BD8                   mov     ebx, eax
004D4ECC   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4ECF   8B8030030000           mov     eax, [eax+$0330]

* Reference to field TListView.Items : TListItems
|
004D4ED5   8B802C020000           mov     eax, [eax+$022C]
004D4EDB   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4EDD   E89E93F8FF             call    0045E280

* Reference to field TListItems.OFFS_000C
|
004D4EE2   8B500C                 mov     edx, [eax+$0C]
004D4EE5   52                     push    edx

* Reference to field TListItems.OFFS_0010
|
004D4EE6   8B5010                 mov     edx, [eax+$10]
004D4EE9   52                     push    edx

* Reference to field TListItems.OFFS_0024
|
004D4EEA   8B4824                 mov     ecx, [eax+$24]
004D4EED   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4EF0   8B802C030000           mov     eax, [eax+$032C]
004D4EF6   8BD6                   mov     edx, esi

* Reference to : TfrmSetupCols._PROC_004D44DC()
|
004D4EF8   E8DFF5FFFF             call    004D44DC
004D4EFD   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4F00   8B8030030000           mov     eax, [eax+$0330]

* Reference to field TListView.Items : TListItems
|
004D4F06   8B802C020000           mov     eax, [eax+$022C]
004D4F0C   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4F0E   E8399CF8FF             call    0045EB4C
004D4F13   EB67                   jmp     004D4F7C
004D4F15   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4F18   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D4F1E   E831F6FFFF             call    004D4554
004D4F23   8BD8                   mov     ebx, eax
004D4F25   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4F28   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4F2E   8B802C020000           mov     eax, [eax+$022C]
004D4F34   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4F36   E84593F8FF             call    0045E280

* Reference to field TListItems.OFFS_000C
|
004D4F3B   8B500C                 mov     edx, [eax+$0C]
004D4F3E   52                     push    edx

* Reference to field TListItems.OFFS_0010
|
004D4F3F   8B5010                 mov     edx, [eax+$10]
004D4F42   52                     push    edx

* Reference to field TListItems.OFFS_0024
|
004D4F43   8B4824                 mov     ecx, [eax+$24]
004D4F46   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4F49   8B802C030000           mov     eax, [eax+$032C]
004D4F4F   8BD6                   mov     edx, esi

* Reference to : TfrmSetupCols._PROC_004D44DC()
|
004D4F51   E886F5FFFF             call    004D44DC
004D4F56   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4F59   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D4F5F   E8F0F5FFFF             call    004D4554
004D4F64   8BD8                   mov     ebx, eax
004D4F66   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4F69   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4F6F   8B802C020000           mov     eax, [eax+$022C]
004D4F75   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4F77   E8D09BF8FF             call    0045EB4C
004D4F7C   33C0                   xor     eax, eax
004D4F7E   5A                     pop     edx
004D4F7F   59                     pop     ecx
004D4F80   59                     pop     ecx
004D4F81   648910                 mov     fs:[eax], edx

****** FINALLY
|
004D4F84   68AD4F4D00             push    $004D4FAD
004D4F89   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4F8C   8B802C030000           mov     eax, [eax+$032C]

* Reference to field TListView.Items : TListItems
|
004D4F92   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.EndUpdate(TListItems);
|
004D4F98   E8A395F8FF             call    0045E540
004D4F9D   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TfrmSetupCols._PROC_004D457C()
|
004D4FA0   E8D7F5FFFF             call    004D457C
004D4FA5   C3                     ret


* Reference to: System.@HandleFinally;
|
004D4FA6   E96DF4F2FF             jmp     00404418
004D4FAB   EBDC                   jmp     004D4F89

****** END
|
004D4FAD   5E                     pop     esi
004D4FAE   5B                     pop     ebx
004D4FAF   59                     pop     ecx
004D4FB0   5D                     pop     ebp
004D4FB1   C20800                 ret     $0008

*)
end;

procedure TfrmSetupCols.LVSelectItem(Sender : TObject);
begin
(*
004D4FB4   55                     push    ebp
004D4FB5   8BEC                   mov     ebp, esp

* Reference to : TfrmSetupCols._PROC_004D457C()
|
004D4FB7   E8C0F5FFFF             call    004D457C
004D4FBC   5D                     pop     ebp
004D4FBD   C20400                 ret     $0004

*)
end;

procedure TfrmSetupCols.btnHelpClick(Sender : TObject);
begin
(*
004D4FC0   55                     push    ebp
004D4FC1   8BEC                   mov     ebp, esp
004D4FC3   8B15482B5000           mov     edx, [$00502B48]
004D4FC9   8B12                   mov     edx, [edx]

* Reference to field TfrmSetupCols.HelpContext : THelpContext
|
004D4FCB   8B8858010000           mov     ecx, [eax+$0158]
004D4FD1   B801000000             mov     eax, $00000001
004D4FD6   92                     xchg    eax, edx

* Reference to: ActiveX.PROPSETHDR_OSVER_KIND(DWORD):Word;
|
004D4FD7   E84825FCFF             call    00497524
004D4FDC   5D                     pop     ebp
004D4FDD   C3                     ret

*)
end;

procedure TfrmSetupCols._PROC_004D4468(Sender : TObject);
begin
(*
004D4468   55                     push    ebp
004D4469   8BEC                   mov     ebp, esp
004D446B   51                     push    ecx
004D446C   53                     push    ebx
004D446D   56                     push    esi
004D446E   8BF1                   mov     esi, ecx
004D4470   8955FC                 mov     [ebp-$04], edx
004D4473   8BD8                   mov     ebx, eax
004D4475   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
004D4478   E8CB0AF3FF             call    00404F48
004D447D   33C0                   xor     eax, eax
004D447F   55                     push    ebp
004D4480   68CD444D00             push    $004D44CD

***** TRY
|
004D4485   64FF30                 push    dword ptr fs:[eax]
004D4488   648920                 mov     fs:[eax], esp

* Reference to field TfrmSetupCols.OFFS_022C
|
004D448B   8B832C020000           mov     eax, [ebx+$022C]

* Reference to: ComCtrls.THeaderSections.Add(THeaderSections):THeaderSection;
|
004D4491   E8529DF8FF             call    0045E1E8
004D4496   8BD8                   mov     ebx, eax
004D4498   8B55FC                 mov     edx, [ebp-$04]
004D449B   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TListItem.SetCaption(TListItem;AnsiString);
|
004D449D   E8B697F8FF             call    0045DC58
004D44A2   8BD6                   mov     edx, esi
004D44A4   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TListItem.SetData(TListItem;Pointer);
|
004D44A6   E85D98F8FF             call    0045DD08
004D44AB   8B4D08                 mov     ecx, [ebp+$08]
004D44AE   33D2                   xor     edx, edx
004D44B0   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D44B2   E88999F8FF             call    0045DE40
004D44B7   33C0                   xor     eax, eax
004D44B9   5A                     pop     edx
004D44BA   59                     pop     ecx
004D44BB   59                     pop     ecx
004D44BC   648910                 mov     fs:[eax], edx

****** FINALLY
|
004D44BF   68D4444D00             push    $004D44D4
004D44C4   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
004D44C7   E8CC05F3FF             call    00404A98
004D44CC   C3                     ret


* Reference to: System.@HandleFinally;
|
004D44CD   E946FFF2FF             jmp     00404418
004D44D2   EBF0                   jmp     004D44C4

****** END
|
004D44D4   5E                     pop     esi
004D44D5   5B                     pop     ebx
004D44D6   59                     pop     ecx
004D44D7   5D                     pop     ebp
004D44D8   C20400                 ret     $0004

*)
end;

procedure TfrmSetupCols._PROC_004D44DC(Sender : TObject);
begin
(*
004D44DC   55                     push    ebp
004D44DD   8BEC                   mov     ebp, esp
004D44DF   51                     push    ecx
004D44E0   53                     push    ebx
004D44E1   56                     push    esi
004D44E2   894DFC                 mov     [ebp-$04], ecx
004D44E5   8BF2                   mov     esi, edx
004D44E7   8BD8                   mov     ebx, eax
004D44E9   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
004D44EC   E8570AF3FF             call    00404F48
004D44F1   33C0                   xor     eax, eax
004D44F3   55                     push    ebp
004D44F4   6844454D00             push    $004D4544

***** TRY
|
004D44F9   64FF30                 push    dword ptr fs:[eax]
004D44FC   648920                 mov     fs:[eax], esp
004D44FF   8BD6                   mov     edx, esi

* Reference to field TfrmSetupCols.OFFS_022C
|
004D4501   8B832C020000           mov     eax, [ebx+$022C]

* Reference to: ComCtrls.TStatusPanels.Insert(TStatusPanels;Integer):TStatusPanel;
|
004D4507   E8E89CF8FF             call    0045E1F4
004D450C   8BD8                   mov     ebx, eax
004D450E   8B55FC                 mov     edx, [ebp-$04]
004D4511   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TListItem.SetCaption(TListItem;AnsiString);
|
004D4513   E84097F8FF             call    0045DC58
004D4518   8B550C                 mov     edx, [ebp+$0C]
004D451B   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TListItem.SetData(TListItem;Pointer);
|
004D451D   E8E697F8FF             call    0045DD08
004D4522   8B4D08                 mov     ecx, [ebp+$08]
004D4525   33D2                   xor     edx, edx
004D4527   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D4529   E81299F8FF             call    0045DE40
004D452E   33C0                   xor     eax, eax
004D4530   5A                     pop     edx
004D4531   59                     pop     ecx
004D4532   59                     pop     ecx
004D4533   648910                 mov     fs:[eax], edx

****** FINALLY
|
004D4536   684B454D00             push    $004D454B
004D453B   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
004D453E   E85505F3FF             call    00404A98
004D4543   C3                     ret


* Reference to: System.@HandleFinally;
|
004D4544   E9CFFEF2FF             jmp     00404418
004D4549   EBF0                   jmp     004D453B

****** END
|
004D454B   5E                     pop     esi
004D454C   5B                     pop     ebx
004D454D   59                     pop     ecx
004D454E   5D                     pop     ebp
004D454F   C20800                 ret     $0008

*)
end;

procedure TfrmSetupCols._PROC_004D4554(Sender : TObject);
begin
(*
004D4554   55                     push    ebp
004D4555   8BEC                   mov     ebp, esp
004D4557   53                     push    ebx
004D4558   8BD8                   mov     ebx, eax
004D455A   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TCustomListView.GetSelected(TCustomListView):TListItem;
|
004D455C   E8C7D3F8FF             call    00461928
004D4561   85C0                   test    eax, eax
004D4563   740F                   jz      004D4574
004D4565   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TCustomListView.GetSelected(TCustomListView):TListItem;
|
004D4567   E8BCD3F8FF             call    00461928

* Reference to: ComCtrls.TListItem.GetIndex(TListItem):Integer;
|
004D456C   E84B9BF8FF             call    0045E0BC
004D4571   5B                     pop     ebx
004D4572   5D                     pop     ebp
004D4573   C3                     ret

004D4574   83C8FF                 or      eax, -$01
004D4577   5B                     pop     ebx
004D4578   5D                     pop     ebp
004D4579   C3                     ret

*)
end;

procedure TfrmSetupCols._PROC_004D457C(Sender : TObject);
begin
(*
004D457C   55                     push    ebp
004D457D   8BEC                   mov     ebp, esp
004D457F   83C4F4                 add     esp, -$0C
004D4582   53                     push    ebx
004D4583   56                     push    esi
004D4584   57                     push    edi
004D4585   8BD8                   mov     ebx, eax

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4587   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D458D   E8C2FFFFFF             call    004D4554
004D4592   8BF0                   mov     esi, eax

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4594   8B8330030000           mov     eax, [ebx+$0330]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D459A   E8B5FFFFFF             call    004D4554
004D459F   40                     inc     eax
004D45A0   0F95C2                 setnz   dl

* Reference to control TfrmSetupCols.btnAdd : TButton
|
004D45A3   8B830C030000           mov     eax, [ebx+$030C]
004D45A9   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
004D45AB   FF5164                 call    dword ptr [ecx+$64]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D45AE   8B8330030000           mov     eax, [ebx+$0330]

* Reference to field TListView.Items : TListItems
|
004D45B4   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D45BA   E8919CF8FF             call    0045E250
004D45BF   85C0                   test    eax, eax
004D45C1   0F9FC2                 setnle  dl

* Reference to control TfrmSetupCols.btnAddAll : TButton
|
004D45C4   8B8310030000           mov     eax, [ebx+$0310]
004D45CA   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
004D45CC   FF5164                 call    dword ptr [ecx+$64]
004D45CF   83FEFF                 cmp     esi, -$01
004D45D2   0F95C2                 setnz   dl

* Reference to control TfrmSetupCols.btnRemove : TButton
|
004D45D5   8B8314030000           mov     eax, [ebx+$0314]
004D45DB   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
004D45DD   FF5164                 call    dword ptr [ecx+$64]

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D45E0   8B832C030000           mov     eax, [ebx+$032C]

* Reference to field TListView.Items : TListItems
|
004D45E6   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D45EC   E85F9CF8FF             call    0045E250
004D45F1   85C0                   test    eax, eax
004D45F3   0F9FC2                 setnle  dl

* Reference to control TfrmSetupCols.btnRemoveAll : TButton
|
004D45F6   8B8318030000           mov     eax, [ebx+$0318]
004D45FC   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
004D45FE   FF5164                 call    dword ptr [ecx+$64]
004D4601   85F6                   test    esi, esi
004D4603   0F9FC2                 setnle  dl

* Reference to control TfrmSetupCols.btnUp : TButton
|
004D4606   8B834C030000           mov     eax, [ebx+$034C]
004D460C   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
004D460E   FF5164                 call    dword ptr [ecx+$64]
004D4611   83FEFF                 cmp     esi, -$01
004D4614   7416                   jz      004D462C

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4616   8B832C030000           mov     eax, [ebx+$032C]

* Reference to field TListView.Items : TListItems
|
004D461C   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D4622   E8299CF8FF             call    0045E250
004D4627   48                     dec     eax
004D4628   3BF0                   cmp     esi, eax
004D462A   7504                   jnz     004D4630
004D462C   33D2                   xor     edx, edx
004D462E   EB02                   jmp     004D4632
004D4630   B201                   mov     dl, $01

* Reference to control TfrmSetupCols.btnDown : TButton
|
004D4632   8B8350030000           mov     eax, [ebx+$0350]
004D4638   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
004D463A   FF5164                 call    dword ptr [ecx+$64]
004D463D   83FEFF                 cmp     esi, -$01
004D4640   7416                   jz      004D4658

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D4642   8B832C030000           mov     eax, [ebx+$032C]

* Reference to field TListView.Items : TListItems
|
004D4648   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.GetCount(TListItems):Integer;
|
004D464E   E8FD9BF8FF             call    0045E250
004D4653   48                     dec     eax
004D4654   3BF0                   cmp     esi, eax
004D4656   7504                   jnz     004D465C
004D4658   33C9                   xor     ecx, ecx
004D465A   EB02                   jmp     004D465E
004D465C   B101                   mov     cl, $01

* Reference to control TfrmSetupCols.udWidth : TUpDown
|
004D465E   8BBB34030000           mov     edi, [ebx+$0334]
004D4664   897DF4                 mov     [ebp-$0C], edi
004D4667   8B870C020000           mov     eax, [edi+$020C]
004D466D   8945F8                 mov     [ebp-$08], eax

* Reference to control TfrmSetupCols.lblWidth : TLabel
|
004D4670   8B8308030000           mov     eax, [ebx+$0308]
004D4676   8945FC                 mov     [ebp-$04], eax
004D4679   8D45F4                 lea     eax, [ebp-$0C]
004D467C   BA02000000             mov     edx, $00000002

* Reference to : TCustomToolWindow97._PROC_004A0D44()
|
004D4681   E8BEC6FCFF             call    004A0D44
004D4686   83FEFF                 cmp     esi, -$01
004D4689   742F                   jz      004D46BA

* Reference to control TfrmSetupCols.lvCur : TListView
|
004D468B   8B832C030000           mov     eax, [ebx+$032C]

* Reference to field TListView.Items : TListItems
|
004D4691   8B802C020000           mov     eax, [eax+$022C]
004D4697   8BD6                   mov     edx, esi

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4699   E8E29BF8FF             call    0045E280

* Reference to field TListItems.OFFS_000C
|
004D469E   8B400C                 mov     eax, [eax+$0C]
004D46A1   8D0440                 lea     eax, [eax+eax*2]

* Reference to field TfrmSetupCols.OFFS_0358
|
004D46A4   8B9358030000           mov     edx, [ebx+$0358]
004D46AA   668B5482F8             mov     dx, word ptr [edx+eax*4-$08]

* Reference to control TfrmSetupCols.udWidth : TUpDown
|
004D46AF   8B8334030000           mov     eax, [ebx+$0334]

* Reference to: ComCtrls.TCustomUpDown.SetPosition(TCustomUpDown;Smallint);
|
004D46B5   E8D681F8FF             call    0045C890
004D46BA   46                     inc     esi
004D46BB   0F95C1                 setnz   cl

* Reference to control TfrmSetupCols.lblSort : TLabel
|
004D46BE   8B831C030000           mov     eax, [ebx+$031C]
004D46C4   8945F4                 mov     [ebp-$0C], eax

* Reference to control TfrmSetupCols.btnSortUp : TBitBtn
|
004D46C7   8B8320030000           mov     eax, [ebx+$0320]
004D46CD   8945F8                 mov     [ebp-$08], eax

* Reference to control TfrmSetupCols.btnSortDown : TBitBtn
|
004D46D0   8B8324030000           mov     eax, [ebx+$0324]
004D46D6   8945FC                 mov     [ebp-$04], eax
004D46D9   8D45F4                 lea     eax, [ebp-$0C]
004D46DC   BA02000000             mov     edx, $00000002

* Reference to : TCustomToolWindow97._PROC_004A0D44()
|
004D46E1   E85EC6FCFF             call    004A0D44
004D46E6   5F                     pop     edi
004D46E7   5E                     pop     esi
004D46E8   5B                     pop     ebx
004D46E9   8BE5                   mov     esp, ebp
004D46EB   5D                     pop     ebp
004D46EC   C3                     ret

*)
end;

procedure TfrmSetupCols._PROC_004D46F0(Sender : TObject);
begin
(*
004D46F0   55                     push    ebp
004D46F1   8BEC                   mov     ebp, esp
004D46F3   53                     push    ebx
004D46F4   56                     push    esi
004D46F5   84D2                   test    dl, dl
004D46F7   7408                   jz      004D4701
004D46F9   83C4F0                 add     esp, -$10

* Reference to: System.@ClassCreate(TClass;Boolean):TObject;
|
004D46FC   E8E7F8F2FF             call    00403FE8
004D4701   8BDA                   mov     ebx, edx
004D4703   8BF0                   mov     esi, eax

* Reference to field TfrmSetupCols.OFFS_0354
|
004D4705   898E54030000           mov     [esi+$0354], ecx
004D470B   8B4510                 mov     eax, [ebp+$10]

* Reference to field TfrmSetupCols.OFFS_0358
|
004D470E   898658030000           mov     [esi+$0358], eax
004D4714   8B450C                 mov     eax, [ebp+$0C]

* Reference to field TfrmSetupCols.OFFS_035C
|
004D4717   89865C030000           mov     [esi+$035C], eax
004D471D   8B4508                 mov     eax, [ebp+$08]

* Reference to field TfrmSetupCols.OFFS_0360
|
004D4720   898660030000           mov     [esi+$0360], eax
004D4726   A168265000             mov     eax, dword ptr [$00502668]
004D472B   8B00                   mov     eax, [eax]

* Reference to field TfrmSetupCols.OFFS_0364
|
004D472D   898664030000           mov     [esi+$0364], eax
004D4733   A1E4255000             mov     eax, dword ptr [$005025E4]
004D4738   8A00                   mov     al, byte ptr [eax]

* Reference to field TfrmSetupCols.OFFS_0368 : Byte
|
004D473A   888668030000           mov     [esi+$0368], al
004D4740   8B0D482B5000           mov     ecx, [$00502B48]
004D4746   8B09                   mov     ecx, [ecx]
004D4748   33D2                   xor     edx, edx
004D474A   8BC6                   mov     eax, esi

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
004D474C   E84BAEFBFF             call    0048F59C
004D4751   8BC6                   mov     eax, esi
004D4753   84DB                   test    bl, bl
004D4755   740F                   jz      004D4766

* Reference to: System.@AfterConstruction(TObject):TObject;
|
004D4757   E8E4F8F2FF             call    00404040
004D475C   648F0500000000         pop     dword ptr fs:[$00000000]
004D4763   83C40C                 add     esp, +$0C
004D4766   8BC6                   mov     eax, esi
004D4768   5E                     pop     esi
004D4769   5B                     pop     ebx
004D476A   5D                     pop     ebp
004D476B   C20C00                 ret     $000C

*)
end;

procedure TfrmSetupCols._PROC_004D48FC(Sender : TObject);
begin
(*
004D48FC   FC                     cld
004D48FD   FFFF                   DB  $FF, $FF  //      
004D48FF   8BD8                   mov     ebx, eax
004D4901   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmSetupCols.lvAvail : TListView
|
004D4904   8B8030030000           mov     eax, [eax+$0330]

* Reference to field TListView.Items : TListItems
|
004D490A   8B802C020000           mov     eax, [eax+$022C]
004D4910   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4912   E86999F8FF             call    0045E280

* Reference to field TListItems.OFFS_0010
|
004D4917   8B5010                 mov     edx, [eax+$10]
004D491A   52                     push    edx

* Reference to field TListItems.OFFS_000C
|
004D491B   8B480C                 mov     ecx, [eax+$0C]

* Reference to field TListItems.OFFS_0024
|
004D491E   8B5024                 mov     edx, [eax+$24]
004D4921   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4924   8B802C030000           mov     eax, [eax+$032C]

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D492A   E839FBFFFF             call    004D4468
004D492F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime1 : N.A.
|
004D4932   8B8030030000           mov     eax, [eax+$0330]

* Reference to field N.A..OFFS_022C
|
004D4938   8B802C020000           mov     eax, [eax+$022C]
004D493E   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4940   E807A2F8FF             call    0045EB4C
004D4945   E9A2020000             jmp     004D4BEC
004D494A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime1 : N.A.
|
004D494D   8B8030030000           mov     eax, [eax+$0330]

* Reference to field N.A..OFFS_022C
|
004D4953   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TTreeNodes.GetCount(TTreeNodes):Integer;
|
004D4959   E8F298F8FF             call    0045E250
004D495E   8BD8                   mov     ebx, eax
004D4960   4B                     dec     ebx
004D4961   85DB                   test    ebx, ebx
004D4963   7C35                   jl      004D499A
004D4965   43                     inc     ebx
004D4966   33F6                   xor     esi, esi
004D4968   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime1 : N.A.
|
004D496B   8B8030030000           mov     eax, [eax+$0330]

* Reference to field N.A..OFFS_022C
|
004D4971   8B802C020000           mov     eax, [eax+$022C]
004D4977   8BD6                   mov     edx, esi

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4979   E80299F8FF             call    0045E280
004D497E   8B5010                 mov     edx, [eax+$10]
004D4981   52                     push    edx
004D4982   8B480C                 mov     ecx, [eax+$0C]
004D4985   8B5024                 mov     edx, [eax+$24]
004D4988   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D498B   8B802C030000           mov     eax, [eax+$032C]

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D4991   E8D2FAFFFF             call    004D4468
004D4996   46                     inc     esi
004D4997   4B                     dec     ebx
004D4998   75CE                   jnz     004D4968
004D499A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime1 : N.A.
|
004D499D   8B8030030000           mov     eax, [eax+$0330]

* Reference to field N.A..OFFS_022C
|
004D49A3   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.Clear(TListItems);
|
004D49A9   E89699F8FF             call    0045E344
004D49AE   E939020000             jmp     004D4BEC
004D49B3   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D49B6   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D49BC   E893FBFFFF             call    004D4554
004D49C1   8BD8                   mov     ebx, eax
004D49C3   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D49C6   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D49CC   8B802C020000           mov     eax, [eax+$022C]
004D49D2   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D49D4   E8A798F8FF             call    0045E280
004D49D9   8B5010                 mov     edx, [eax+$10]
004D49DC   52                     push    edx
004D49DD   8B480C                 mov     ecx, [eax+$0C]
004D49E0   8B5024                 mov     edx, [eax+$24]
004D49E3   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime1 : N.A.
|
004D49E6   8B8030030000           mov     eax, [eax+$0330]

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D49EC   E877FAFFFF             call    004D4468
004D49F1   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D49F4   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D49FA   8B802C020000           mov     eax, [eax+$022C]
004D4A00   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4A02   E845A1F8FF             call    0045EB4C
004D4A07   E9E0010000             jmp     004D4BEC
004D4A0C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4A0F   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4A15   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TTreeNodes.GetCount(TTreeNodes):Integer;
|
004D4A1B   E83098F8FF             call    0045E250
004D4A20   8BD8                   mov     ebx, eax
004D4A22   4B                     dec     ebx
004D4A23   85DB                   test    ebx, ebx
004D4A25   7C35                   jl      004D4A5C
004D4A27   43                     inc     ebx
004D4A28   33F6                   xor     esi, esi
004D4A2A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4A2D   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4A33   8B802C020000           mov     eax, [eax+$022C]
004D4A39   8BD6                   mov     edx, esi

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4A3B   E84098F8FF             call    0045E280
004D4A40   8B5010                 mov     edx, [eax+$10]
004D4A43   52                     push    edx
004D4A44   8B480C                 mov     ecx, [eax+$0C]
004D4A47   8B5024                 mov     edx, [eax+$24]
004D4A4A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime1 : N.A.
|
004D4A4D   8B8030030000           mov     eax, [eax+$0330]

* Reference to: ComCtrls.TCustomListView.AddItem(TCustomListView;AnsiString;TObject);
|
004D4A53   E810FAFFFF             call    004D4468
004D4A58   46                     inc     esi
004D4A59   4B                     dec     ebx
004D4A5A   75CE                   jnz     004D4A2A
004D4A5C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4A5F   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4A65   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.Clear(TListItems);
|
004D4A6B   E8D498F8FF             call    0045E344
004D4A70   E977010000             jmp     004D4BEC
004D4A75   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4A78   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D4A7E   E8D1FAFFFF             call    004D4554
004D4A83   8BD8                   mov     ebx, eax
004D4A85   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4A88   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4A8E   8B802C020000           mov     eax, [eax+$022C]
004D4A94   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4A96   E8E597F8FF             call    0045E280
004D4A9B   8B500C                 mov     edx, [eax+$0C]
004D4A9E   52                     push    edx
004D4A9F   8B5010                 mov     edx, [eax+$10]
004D4AA2   52                     push    edx
004D4AA3   8B4824                 mov     ecx, [eax+$24]
004D4AA6   8BF3                   mov     esi, ebx
004D4AA8   4E                     dec     esi
004D4AA9   8BD6                   mov     edx, esi
004D4AAB   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4AAE   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D44DC()
|
004D4AB4   E823FAFFFF             call    004D44DC

* Reference to field N.A..OFFS_0001
|
004D4AB9   8D5301                 lea     edx, [ebx+$01]
004D4ABC   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4ABF   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4AC5   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4ACB   E87CA0F8FF             call    0045EB4C
004D4AD0   8BD6                   mov     edx, esi
004D4AD2   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4AD5   8BB82C030000           mov     edi, [eax+$032C]
004D4ADB   8B872C020000           mov     eax, [edi+$022C]

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4AE1   E89A97F8FF             call    0045E280
004D4AE6   8BD0                   mov     edx, eax
004D4AE8   8BC7                   mov     eax, edi

* Reference to: ComCtrls.TCustomListView.SetSelected(TCustomListView;TListItem);
|
004D4AEA   E851CEF8FF             call    00461940
004D4AEF   E9F8000000             jmp     004D4BEC
004D4AF4   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4AF7   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D4554()
|
004D4AFD   E852FAFFFF             call    004D4554
004D4B02   8BD8                   mov     ebx, eax
004D4B04   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4B07   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4B0D   8B802C020000           mov     eax, [eax+$022C]
004D4B13   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4B15   E86697F8FF             call    0045E280
004D4B1A   8B500C                 mov     edx, [eax+$0C]
004D4B1D   52                     push    edx
004D4B1E   8B5010                 mov     edx, [eax+$10]
004D4B21   52                     push    edx
004D4B22   8B4824                 mov     ecx, [eax+$24]

* Reference to field N.A..OFFS_0002
|
004D4B25   8D5302                 lea     edx, [ebx+$02]
004D4B28   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4B2B   8B802C030000           mov     eax, [eax+$032C]

* Reference to : TfrmSetupCols._PROC_004D44DC()
|
004D4B31   E8A6F9FFFF             call    004D44DC
004D4B36   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4B39   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4B3F   8B802C020000           mov     eax, [eax+$022C]
004D4B45   8BD3                   mov     edx, ebx

* Reference to: ComCtrls.TListItems.Delete(TListItems;Integer);
|
004D4B47   E800A0F8FF             call    0045EB4C

* Reference to field N.A..OFFS_0001
|
004D4B4C   8D5301                 lea     edx, [ebx+$01]
004D4B4F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4B52   8BB02C030000           mov     esi, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4B58   8B862C020000           mov     eax, [esi+$022C]

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4B5E   E81D97F8FF             call    0045E280
004D4B63   8BD0                   mov     edx, eax
004D4B65   8BC6                   mov     eax, esi

* Reference to: ComCtrls.TCustomListView.SetSelected(TCustomListView;TListItem);
|
004D4B67   E8D4CDF8FF             call    00461940
004D4B6C   EB7E                   jmp     004D4BEC
004D4B6E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4B71   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4B77   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TTreeNodes.GetCount(TTreeNodes):Integer;
|
004D4B7D   E8CE96F8FF             call    0045E250
004D4B82   8BD8                   mov     ebx, eax
004D4B84   4B                     dec     ebx
004D4B85   85DB                   test    ebx, ebx
004D4B87   7C27                   jl      004D4BB0
004D4B89   43                     inc     ebx
004D4B8A   33F6                   xor     esi, esi
004D4B8C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4B8F   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4B95   8B802C020000           mov     eax, [eax+$022C]
004D4B9B   8BD6                   mov     edx, esi

* Reference to: ComCtrls.TListItems.GetItem(TListItems;Integer):TListItem;
|
004D4B9D   E8DE96F8FF             call    0045E280
004D4BA2   83C9FF                 or      ecx, -$01
004D4BA5   33D2                   xor     edx, edx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D4BA7   E89492F8FF             call    0045DE40
004D4BAC   46                     inc     esi
004D4BAD   4B                     dec     ebx
004D4BAE   75DC                   jnz     004D4B8C
004D4BB0   837F0C07               cmp     dword ptr [edi+$0C], +$07
004D4BB4   751C                   jnz     004D4BD2
004D4BB6   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4BB9   8B802C030000           mov     eax, [eax+$032C]

* Reference to: ComCtrls.TCustomListView.GetSelected(TCustomListView):TListItem;
|
004D4BBF   E864CDF8FF             call    00461928
004D4BC4   B920000000             mov     ecx, $00000020
004D4BC9   33D2                   xor     edx, edx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D4BCB   E87092F8FF             call    0045DE40
004D4BD0   EB1A                   jmp     004D4BEC
004D4BD2   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4BD5   8B802C030000           mov     eax, [eax+$032C]

* Reference to: ComCtrls.TCustomListView.GetSelected(TCustomListView):TListItem;
|
004D4BDB   E848CDF8FF             call    00461928
004D4BE0   B921000000             mov     ecx, $00000021
004D4BE5   33D2                   xor     edx, edx

* Reference to: ComCtrls.TListItem.SetImage(TListItem;Integer;TImageIndex);
|
004D4BE7   E85492F8FF             call    0045DE40
004D4BEC   33C0                   xor     eax, eax
004D4BEE   5A                     pop     edx
004D4BEF   59                     pop     ecx
004D4BF0   59                     pop     ecx
004D4BF1   648910                 mov     fs:[eax], edx

****** FINALLY
|
004D4BF4   68154C4D00             push    $004D4C15
004D4BF9   8B45FC                 mov     eax, [ebp-$04]

* Reference to control lblTime2 : N.A.
|
004D4BFC   8B802C030000           mov     eax, [eax+$032C]

* Reference to field N.A..OFFS_022C
|
004D4C02   8B802C020000           mov     eax, [eax+$022C]

* Reference to: ComCtrls.TTreeNodes.EndUpdate(TTreeNodes);
|
004D4C08   E83399F8FF             call    0045E540
004D4C0D   C3                     ret


* Reference to: System.@HandleFinally;
|
004D4C0E   E905F8F2FF             jmp     00404418
004D4C13   EBE4                   jmp     004D4BF9

****** END
|
004D4C15   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TfrmSetupCols._PROC_004D457C()
|
004D4C18   E85FF9FFFF             call    004D457C
004D4C1D   5F                     pop     edi
004D4C1E   5E                     pop     esi
004D4C1F   5B                     pop     ebx
004D4C20   59                     pop     ecx
004D4C21   5D                     pop     ebp
004D4C22   C3                     ret

*)
end;

procedure TfrmSetupCols._PROC_004D4FE0(Sender : TObject);
begin
(*
004D4FE0   55                     push    ebp
004D4FE1   8BEC                   mov     ebp, esp
004D4FE3   33C0                   xor     eax, eax
004D4FE5   55                     push    ebp
004D4FE6   6805504D00             push    $004D5005

***** TRY
|
004D4FEB   64FF30                 push    dword ptr fs:[eax]
004D4FEE   648920                 mov     fs:[eax], esp
004D4FF1   FF05B4455000           inc     dword ptr [$005045B4]
004D4FF7   33C0                   xor     eax, eax
004D4FF9   5A                     pop     edx
004D4FFA   59                     pop     ecx
004D4FFB   59                     pop     ecx
004D4FFC   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-´EP'
|
004D4FFF   680C504D00             push    $004D500C
004D5004   C3                     ret


* Reference to: System.@HandleFinally;
|
004D5005   E90EF4F2FF             jmp     00404418
004D500A   EBF8                   jmp     004D5004

****** END
|
004D500C   5D                     pop     ebp
004D500D   C3                     ret

*)
end;

procedure TfrmSetupCols._PROC_004D5010(Sender : TObject);
begin
(*
004D5010   832DB445500001         sub     dword ptr [$005045B4], +$01
004D5017   C3                     ret

*)
end;

procedure TfrmSetupCols._PROC_004D5018(Sender : TObject);
begin
(*
004D5018   6450                   push    eax
004D501A   4D                     dec     ebp
004D501B   0000                   add     [eax], al

*)
end;

procedure TfrmSetupCols._PROC_004D50A2(Sender : TObject);
begin
(*
004D50A2   47                     inc     edi
004D50A3   00B4CB4700A401         add     [ebx+ecx*8+$1A40047], dh
004D50AA   49                     dec     ecx
004D50AB   00EC                   add     ah, ch
004D50AD   C847                   enter   , $47
004D50AF   00645447               add     [esp+edx*2+$47], ah
004D50B3   006854                 add     [eax+$54], ch
004D50B6   47                     inc     edi
004D50B7   0098024900C8           add     [eax+$C8004902], bl
004D50BD   844700                 test    [edi+$00], al
004D50C0   A85F                   test    al, $5F
004D50C2   47                     inc     edi
004D50C3   00E0                   add     al, ah
004D50C5   55                     push    ebp
004D50C6   47                     inc     edi
004D50C7   003461                 add     [ecx], dh
004D50CA   47                     inc     edi
004D50CB   008C0449005803         add     [esp+eax+$3580049], cl
004D50D2   49                     dec     ecx
004D50D3   006C6247               add     [edx+$47], ch
004D50D7   00040549004C85         add     [$854C0049+eax], al
004D50DE   47                     inc     edi
004D50DF   0040C9                 add     [eax-$37], al
004D50E2   47                     inc     edi
004D50E3   00FC                   add     ah, bh
004D50E5   C9                     leave
004D50E6   47                     inc     edi
004D50E7   00F8                   add     al, bh
004D50E9   C44700                 les     eax, [edi+$00]
004D50EC   E0C9                   loopn   -$37
004D50EE   47                     inc     edi
004D50EF   00A4F34800A80B         add     [ebx+esi*8+$BA80048], ah
004D50F6   49                     dec     ecx
004D50F7   00AC9F47006C18         add     [edi+ebx*4+$186C0047], ch
004D50FE   49                     dec     ecx
004D50FF   00CC                   add     ah, cl
004D5101   1B4900                 sbb     ecx, [ecx+$00]
004D5104   881A                   mov     [edx], bl
004D5106   49                     dec     ecx
004D5107   0044A047               add     [eax+$47], al
004D510B   0048A0                 add     [eax-$60], cl
004D510E   47                     inc     edi
004D510F   00041D4900A89E         add     [$9EA80049+ebx], al
004D5116   47                     inc     edi
004D5117   0020                   add     [eax], ah
004D5119   CB                     ret

*)
end;

procedure TfrmSetupCols._PROC_004D511A(Sender : TObject);
begin
(*
004D511A   47                     inc     edi
004D511B   00F8                   add     al, bh
004D511D   234900                 and     ecx, [ecx+$00]
004D5120   14DD                   adc     al, $DD
004D5122   47                     inc     edi
004D5123   009CC747000C39         add     [edi+eax*8+$390C0047], bl
004D512A   49                     dec     ecx
004D512B   0098ED480048           add     [eax+$480048ED], bl
004D5131   F0                     lock
004D5132   48                     dec     eax
004D5133   00EC                   add     ah, ch
004D5135   294900                 sub     dword ptr [ecx+$00], ecx
004D5138   28FA                   sub     dl, bh
004D513A   48                     dec     eax
004D513B   00A4FA4800EC3C         add     [edx+edi*8+$3CEC0048], ah
004D5142   49                     dec     ecx
004D5143   0060F7                 add     [eax-$09], ah
004D5146   48                     dec     eax
004D5147   00F0                   add     al, dh
004D5149   37                     aaa
004D514A   49                     dec     ecx
004D514B   00D0                   add     al, dl
004D514D   1E                     push    ds
004D514E   49                     dec     ecx
004D514F   00A43949008804         add     [ecx+edi+$4880049], ah
004D5156   49                     dec     ecx
004D5157   0007                   add     [edi], al
004D5159   00F8                   add     al, bh
004D515B   51                     push    ecx
004D515C   4D                     dec     ebp
004D515D   00F8                   add     al, bh
004D515F   0200                   add     al, byte ptr [eax]
004D5161   0000                   add     [eax], al

*)
end;

end.